2020-12-02 17:38:32,164 ERROR [root] [Log2.py(Log2:32)] - error
